name: webdriverIO-tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: allure
    env:
      USERNAME: ${{ secrets.LOGIN_USERNAME }}
      PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
          
      - name: Install dependencies
        run: |
          npm install
            
      - name: Run all tests
        run: npm run wdio
          
      # - name: Store Allure History
      #   if: always()
      #   run: |
      #     mkdir -p allure-history
      #     cp -r allure-report/history allure-history/

      - name: Clone GitHub Pages Branch
        run: |
          git clone --branch gh-pages --single-branch --depth 1 https://github.com/${{ github.repository }} allure-history
          cd ./allure-history
          ls -R
          # cp -r allure-history/history allure-results/

      # - name: List Directory Contents
      #   run: |
      #     cd allure-history
      #     ls -R
      #     cd allure-results
      #     ls -R
          
      - name: List Folder Structure
        run: |
          cd $GITHUB_WORKSPACE
          ls -R

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
