name: webdriverIO-tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: allure
    env:
      USERNAME: ${{ secrets.LOGIN_USERNAME }}
      PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
          
      - name: Install dependencies
        run: |
          npm install
            
      - name: Run all tests
        run: npm run wdio
          
      - name: Preserve Allure History
        run: |
          mkdir -p allure-results/history
          cp -r allure-report/history allure-results/

      - name: Clone gh-pages Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy Allure Report to gh-pages Branch
        run: |
          mkdir -p gh-pages/allure-report
          cp -r allure-report/* gh-pages/allure-report

      - name: Copy Allure History to gh-pages Branch
        run: |
          mkdir -p gh-pages/allure-history
          cp -r allure-results/* gh-pages/allure-history

      - name: Commit and Push Changes
        run: |
          cd gh-pages
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update Allure report"
          git push origin gh-pages
