name: webdriverIO-tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: allure
    env:
      USERNAME: ${{ secrets.LOGIN_USERNAME }}
      PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
          
      - name: Install dependencies
        run: |
          npm install
            
      - name: Run all tests
        run: npm run wdio
          
      - name: Get Allure history (previous run)
        uses: actions/download-artifact@v4
        if: always()
        with:
          name: allure-history
      
      - name: Copy Allure history to working directory
        run: |
          cp -r allure-history/* .
      
      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 5
