name: webdriverIO-tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: allure
    env:
      USERNAME: ${{ secrets.LOGIN_USERNAME }}
      PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        
    steps:
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "Username"
          echo ${{ secrets.LOGIN_USERNAME }}
          echo "Password"
          echo ${{ secrets.LOGIN_PASSWORD }}
        
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
          
      - name: Install dependencies
        run: |
          npm install
            
      - name: Run all tests
        run: npm run wdio
          
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
  
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
