name: webdriverIO-tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: allure
    env:
      USERNAME: ${{ secrets.LOGIN_USERNAME }}
      PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
          
      - name: Install dependencies
        run: |
          npm install

      
      - name: Run all tests
        run: npm run wdio

      - name: Clone GitHub Pages Branch
        run: |
          cd ~
          cd ./work/webdriverIO-Allure/webdriverIO-Allure/
          ls -R
          git clone --branch gh-pages --single-branch --depth 1 https://github.com/${{ github.repository }} allure-history
          cp -r ./allure-report/history allure-history/

      - name: List Folder Structure
        run: |
          cd ~
          # cd ./work/webdriverIO-Allure/webdriverIO-Allure/
          # ls -R
          cd ./work/webdriverIO-Allure/webdriverIO-Allure/allure-results
          mkdir -p history
          cd ~
          cd ./work/webdriverIO-Allure/webdriverIO-Allure
          cp -r allure-history/ allure-results/history
          cd ~
          cd ./work/webdriverIO-Allure/webdriverIO-Allure/allure-results/history
          la -R
          
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
